package autotrader

type SuccessResponse struct {
	Summaries []struct {
		PPGCompanyID              string  `json:"PPGCompanyID"`
		DealerType                int     `json:"DealerType"`
		Status                    string  `json:"Status"`
		Year                      int     `json:"Year"`
		Make                      string  `json:"Make"`
		Model                     string  `json:"Model"`
		SearchMake                string  `json:"SearchMake"`
		SearchModel               string  `json:"SearchModel"`
		SearchTrim                string  `json:"SearchTrim"`
		Trim                      string  `json:"Trim"`
		Price                     float64 `json:"Price"`
		MsrpPrice                 float64 `json:"MsrpPrice"`
		ContactPhoneNumber        string  `json:"ContactPhoneNumber"`
		ContactEmailAddress       string  `json:"ContactEmailAddress"`
		StrikeThroughPrice        float64 `json:"StrikeThroughPrice"`
		Cylinders                 string  `json:"Cylinders"`
		FuelType                  string  `json:"FuelType"`
		Engine                    string  `json:"Engine"`
		Length                    float64 `json:"Length"`
		LengthType                string  `json:"LengthType"`
		HorsePower                string  `json:"HorsePower"`
		NumberOfHours             int     `json:"NumberOfHours"`
		ForeignID                 string  `json:"ForeignId"`
		Transmission              string  `json:"Transmission"`
		DriveTrain                string  `json:"DriveTrain"`
		BodyStyle                 string  `json:"BodyStyle"`
		Mileage                   int     `json:"Mileage"`
		SourceID                  int     `json:"SourceId"`
		HasCar360                 bool    `json:"HasCar360"`
		HasInternalSpin           bool    `json:"HasInternalSpin"`
		HasVideo                  bool    `json:"HasVideo"`
		HasYouTubeVideo           bool    `json:"HasYouTubeVideo"`
		CompanyID                 string  `json:"CompanyId"`
		IsNewCar                  bool    `json:"IsNewCar"`
		IsPassengerVehicle        bool    `json:"IsPassengerVehicle"`
		IsCommercialVehicle       bool    `json:"IsCommercialVehicle"`
		SimilarVehiclesCountLabel string  `json:"SimilarVehiclesCountLabel"`
		Distance                  float64 `json:"Distance"`
		MainPhotoURL              string  `json:"MainPhotoUrl"`
		Media                     struct {
			VideoUrls any `json:"VideoUrls"`
		} `json:"Media"`
		VideoUrls  any   `json:"VideoUrls"`
		PhotoUrls  []any `json:"PhotoUrls"`
		PhotoCount int   `json:"PhotoCount"`
		UpSells    []struct {
			Name      string  `json:"Name"`
			StartDate float64 `json:"StartDate"`
			EndDate   float64 `json:"EndDate"`
			SiteID    int     `json:"SiteId"`
			Value     any     `json:"Value"`
		} `json:"UpSells"`
		Province             string `json:"Province"`
		CategoryPath         string `json:"CategoryPath"`
		FinanceInfoV2        any    `json:"FinanceInfoV2"`
		ContentURL           string `json:"ContentUrl"`
		SimilarVehiclesKey   string `json:"SimilarVehiclesKey"`
		SimilarVehiclesKeyV2 string `json:"SimilarVehiclesKeyV2"`
		Diagnostics          any    `json:"Diagnostics"`
		CarProof             struct {
			CarProofModeName    string `json:"CarProofModeName"`
			CarProofURL         any    `json:"CarProofUrl"`
			CarProofNoAccidents any    `json:"CarProofNoAccidents"`
			CarProofOneOwner    any    `json:"CarProofOneOwner"`
		} `json:"CarProof"`
		SubPrime                 any     `json:"SubPrime"`
		PricingAnalysisCondition string  `json:"PricingAnalysisCondition"`
		PriceDelta               int     `json:"PriceDelta"`
		OlympusDealer            bool    `json:"OlympusDealer"`
		IsTopSpot                bool    `json:"IsTopSpot"`
		IsXPriorityListing       bool    `json:"IsXPriorityListing"`
		IsAwardWinner            bool    `json:"IsAwardWinner"`
		HighlyRatedScore         float64 `json:"HighlyRatedScore"`
		ChatEnabled              bool    `json:"ChatEnabled"`
		HasVirtualAppraisal      bool    `json:"HasVirtualAppraisal"`
		HasOnlineReservation     bool    `json:"HasOnlineReservation"`
		HasTryBeforeYouBuy       bool    `json:"HasTryBeforeYouBuy"`
		HasMoneyBackGuarantee    bool    `json:"HasMoneyBackGuarantee"`
		IsOnlineSellerPlus       bool    `json:"IsOnlineSellerPlus"`
		DealerName               string  `json:"DealerName"`
		Vin                      string  `json:"Vin"`
		IsVirtualDealer          bool    `json:"IsVirtualDealer"`
		AdSortPoint2XsVar1       float64 `json:"AdSortPoint2XsVar1"`
	} `json:"Summaries"`
	TotalSummaries int `json:"TotalSummaries"`
	Diagnostics    any `json:"Diagnostics"`
	Location       struct {
		Latitude             float64 `json:"Latitude"`
		Longitude            float64 `json:"Longitude"`
		City                 string  `json:"City"`
		ProvinceAbbreviation string  `json:"ProvinceAbbreviation"`
		PostalCode           string  `json:"PostalCode"`
	} `json:"Location"`
	ContentURL string `json:"ContentUrl"`
}
